package model.Views.common;

import oracle.jbo.Row;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Fri Feb 23 06:00:56 AST 2018
// ---------------------------------------------------------------------
public interface DepartmentsVORow extends Row {
    oracle.jbo.domain.Number updateEmployeesSal(oracle.jbo.domain.Number upd);

    oracle.jbo.domain.Number updateEmployeesSal1(oracle.jbo.domain.Number upd);

    oracle.jbo.domain.Number updateEmployeesSal2(oracle.jbo.domain.Number upd);

    oracle.jbo.domain.Number updateEmployeesSal3(oracle.jbo.domain.Number upd);

    oracle.jbo.domain.Number updateEmployeesSal4(oracle.jbo.domain.Number upd);
}

