package model.Views;

import model.Entities.MembersEOImpl;

import oracle.jbo.domain.Number;
import oracle.jbo.server.EntityImpl;
import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Mon Feb 19 21:35:14 AST 2018
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class MembersVORowImpl extends ViewRowImpl {

    public static final int ENTITY_MEMBERSEO = 0;

    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    protected enum AttributesEnum {
        FirstName,
        LastName,
        Mobile,
        Email,
        Gender,
        SecurityQuestion,
        QuestionAnswer,
        Password,
        User1,
        Id;
        private static AttributesEnum[] vals = null;
        ;
        private static final int firstIndex = 0;

        protected int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        protected static final int firstIndex() {
            return firstIndex;
        }

        protected static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        protected static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }

    public static final int FIRSTNAME = AttributesEnum.FirstName.index();
    public static final int LASTNAME = AttributesEnum.LastName.index();
    public static final int MOBILE = AttributesEnum.Mobile.index();
    public static final int EMAIL = AttributesEnum.Email.index();
    public static final int GENDER = AttributesEnum.Gender.index();
    public static final int SECURITYQUESTION = AttributesEnum.SecurityQuestion.index();
    public static final int QUESTIONANSWER = AttributesEnum.QuestionAnswer.index();
    public static final int PASSWORD = AttributesEnum.Password.index();
    public static final int USER1 = AttributesEnum.User1.index();
    public static final int ID = AttributesEnum.Id.index();

    /**
     * This is the default constructor (do not remove).
     */
    public MembersVORowImpl() {
    }

    /**
     * Gets MembersEO entity object.
     * @return the MembersEO
     */
    public MembersEOImpl getMembersEO() {
        return (MembersEOImpl) getEntity(ENTITY_MEMBERSEO);
    }

    /**
     * Gets the attribute value for FIRST_NAME using the alias name FirstName.
     * @return the FIRST_NAME
     */
    public String getFirstName() {
        return (String) getAttributeInternal(FIRSTNAME);
    }

    /**
     * Sets <code>value</code> as attribute value for FIRST_NAME using the alias name FirstName.
     * @param value value to set the FIRST_NAME
     */
    public void setFirstName(String value) {
        setAttributeInternal(FIRSTNAME, value);
    }

    /**
     * Gets the attribute value for LAST_NAME using the alias name LastName.
     * @return the LAST_NAME
     */
    public String getLastName() {
        return (String) getAttributeInternal(LASTNAME);
    }

    /**
     * Sets <code>value</code> as attribute value for LAST_NAME using the alias name LastName.
     * @param value value to set the LAST_NAME
     */
    public void setLastName(String value) {
        setAttributeInternal(LASTNAME, value);
    }

    /**
     * Gets the attribute value for MOBILE using the alias name Mobile.
     * @return the MOBILE
     */
    public Number getMobile() {
        return (Number) getAttributeInternal(MOBILE);
    }

    /**
     * Sets <code>value</code> as attribute value for MOBILE using the alias name Mobile.
     * @param value value to set the MOBILE
     */
    public void setMobile(Number value) {
        setAttributeInternal(MOBILE, value);
    }

    /**
     * Gets the attribute value for EMAIL using the alias name Email.
     * @return the EMAIL
     */
    public String getEmail() {
        return (String) getAttributeInternal(EMAIL);
    }

    /**
     * Sets <code>value</code> as attribute value for EMAIL using the alias name Email.
     * @param value value to set the EMAIL
     */
    public void setEmail(String value) {
        setAttributeInternal(EMAIL, value);
    }

    /**
     * Gets the attribute value for GENDER using the alias name Gender.
     * @return the GENDER
     */
    public String getGender() {
        return (String) getAttributeInternal(GENDER);
    }

    /**
     * Sets <code>value</code> as attribute value for GENDER using the alias name Gender.
     * @param value value to set the GENDER
     */
    public void setGender(String value) {
        setAttributeInternal(GENDER, value);
    }

    /**
     * Gets the attribute value for SECURITY_QUESTION using the alias name SecurityQuestion.
     * @return the SECURITY_QUESTION
     */
    public String getSecurityQuestion() {
        return (String) getAttributeInternal(SECURITYQUESTION);
    }

    /**
     * Sets <code>value</code> as attribute value for SECURITY_QUESTION using the alias name SecurityQuestion.
     * @param value value to set the SECURITY_QUESTION
     */
    public void setSecurityQuestion(String value) {
        setAttributeInternal(SECURITYQUESTION, value);
    }

    /**
     * Gets the attribute value for QUESTION_ANSWER using the alias name QuestionAnswer.
     * @return the QUESTION_ANSWER
     */
    public String getQuestionAnswer() {
        return (String) getAttributeInternal(QUESTIONANSWER);
    }

    /**
     * Sets <code>value</code> as attribute value for QUESTION_ANSWER using the alias name QuestionAnswer.
     * @param value value to set the QUESTION_ANSWER
     */
    public void setQuestionAnswer(String value) {
        setAttributeInternal(QUESTIONANSWER, value);
    }

    /**
     * Gets the attribute value for PASSWORD using the alias name Password.
     * @return the PASSWORD
     */
    public String getPassword() {
        return (String) getAttributeInternal(PASSWORD);
    }

    /**
     * Sets <code>value</code> as attribute value for PASSWORD using the alias name Password.
     * @param value value to set the PASSWORD
     */
    public void setPassword(String value) {
        setAttributeInternal(PASSWORD, value);
    }

    /**
     * Gets the attribute value for "USER" using the alias name User1.
     * @return the "USER"
     */
    public String getUser1() {
        return (String) getAttributeInternal(USER1);
    }

    /**
     * Sets <code>value</code> as attribute value for "USER" using the alias name User1.
     * @param value value to set the "USER"
     */
    public void setUser1(String value) {
        setAttributeInternal(USER1, value);
    }

    /**
     * Gets the attribute value for ID using the alias name Id.
     * @return the ID
     */
    public Number getId() {
        return (Number) getAttributeInternal(ID);
    }

    /**
     * Sets <code>value</code> as attribute value for ID using the alias name Id.
     * @param value value to set the ID
     */
    public void setId(Number value) {
        setAttributeInternal(ID, value);
    }
}

