package model.Views;

import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Mon Feb 19 21:35:15 AST 2018
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class MembersVOImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public MembersVOImpl() {
    }
}

