package model.AppModule.common;

import oracle.jbo.ApplicationModule;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Mon Feb 19 22:27:00 AST 2018
// ---------------------------------------------------------------------
public interface AppModuleAM extends ApplicationModule {
    void createAndInitRowNewMemeber(String fName, String LName, oracle.jbo.domain.Number Mobile, String email,
                                    String Gender, String SecQues, String QuesAnswer, String Pass, String userName);

    void createNewMemeberAM(String fName, String LName, oracle.jbo.domain.Number Mobile, String email, String Gender,
                            String SecQues, String QuesAnswer, String Pass, String userName);

    void createNewMemeberVROW(String fName, String LName, oracle.jbo.domain.Number Mobile, String email, String Gender,
                              String SecQues, String QuesAnswer, String Pass, String userName);
}

